### ISSUE TITLE
Error Express Checkout

### ISSUE THREAD

**Issue by ghost** [srmklive/laravel-paypal-demo#14] opened 2017-10-10 07:53 UTC
I get this error while executing Express Checkout

> The Response content must be a string or object implementing __toString(), "object" given.

I tried `dd($response)` , I get this response 

```
array:3 [▼
  "type" => "error"
  "message" => ""
  "paypal_link" => null
]
```

I am using laravel 5.5.14

**Comment by srmklive** [comment] 2017-10-10 10:12
Duplicate of #13. Also refer to this as well srmklive/laravel-paypal#136

**Closed as completed by srmklive** 2017-10-10 10:12 UTC

**Comment by friana** [comment] 2019-03-14 08:44
This issue may be solve in this link. Thanks

https://github.com/srmklive/laravel-paypal/issues/229#issuecomment-472755054

**Comment by pmatisko** [comment] 2019-08-22 23:12
I fought this error on my local PC with Apache and PHP7.2. For some reason restarting the Apache service (on Win10) helped. Now, the response is ok.
